pipeline {
    agent any

    environment {
        GIT_REPO_URL = 'https://github.com/Bhargavreddysudha/simple-maven.git'
        GIT_BRANCH = 'main'
        SONARQUBE_SERVER = 'http://52.87.243.220:9000/'
        S3_BUCKET_NAME = 'test-bukkk'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', 
                          branches: [[name: "*/${GIT_BRANCH}"]], 
                          userRemoteConfigs: [[url: "${GIT_REPO_URL}"]]])
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def mvn = tool 'Maven'

                    withCredentials([string(credentialsId: 'Sonar-Jenkins', variable: 'SONARQUBE_TOKEN')]) {
                        withSonarQubeEnv(credentialsId: 'Sonar-Jenkins', installationName: 'SonarQube') {
                            sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=Java-Code"
                        }
                    }
                }
            }
        }

        stage('Java Package') {
            steps {
                script {
                    def mvn = tool 'Maven'
                    sh "${mvn}/bin/mvn package"
                }
            }
        }

        stage('Move Artifact to S3') {
            steps {
                script {
                    def artifactName = "your-artifact-${env.BUILD_NUMBER}.jar"
                    def sourceArtifactPath = "${env.WORKSPACE}/target/${artifactName}"
                    sh """
                        aws s3 cp ${sourceArtifactPath} s3://${S3_BUCKET_NAME}/
                    """
                }
            }
        }

        stage('Next Stage') {
            steps {
                echo 'Performing actions in the next stage...'
                // Your next stage steps here
            }
        }
    }
}
